apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
  labels:
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name }}
spec:
  hosts:
  - "*"
  gateways:
  - frontend-gateway
  http:
  - route:
    - destination:
        host: frontend-poc
        port:
          number: 80