apiVersion: v1
kind: Service
metadata:
  name: {{ include "adservice.fullname" . }}
  labels:
    {{- include "adservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: adservice
